apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-d
  template:
    metadata:
      labels:
        app: web-d
    spec:
      containers:
        - name: web-d
          imagePullPolicy: Always
          image: lufemunhoz/t_truck_web:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-s
spec:
  selector:
    app: web-d
  ports:
    - port: 80
      nodePort: 30000
  type: NodePort
  # externalIPs:
  #   - '172.17.20.45'
  # type: LoadBalancer se for na nuvem
