apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: lufemunhoz/t_truck_web:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  # externalIPs:
  #   - '172.17.20.45'
  # type: LoadBalancer se for na nuvem
