// Mocks generated by Mockito 5.0.11 from annotations
// in t_truck_web/test/features/home/ui/home_controller_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:t_truck_web/core/components/menu/menu_component_controller.dart'
    as _i3;
import 'package:t_truck_web/core/components/menu/menu_model.dart' as _i4;
import 'package:t_truck_web/core/utils/app_dialog.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [IAppDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAppDialog extends _i1.Mock implements _i2.IAppDialog {
  MockIAppDialog() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void show({String? menssagem}) =>
      super.noSuchMethod(Invocation.method(#show, [], {#menssagem: menssagem}),
          returnValueForMissingStub: null);
  @override
  void error({String? menssagem}) =>
      super.noSuchMethod(Invocation.method(#error, [], {#menssagem: menssagem}),
          returnValueForMissingStub: null);
}

/// A class which mocks [IMenuComponentController].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMenuComponentController extends _i1.Mock
    implements _i3.IMenuComponentController {
  MockIMenuComponentController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addQuickAcces(_i4.MenuModel? menuModel) =>
      super.noSuchMethod(Invocation.method(#addQuickAcces, [menuModel]),
          returnValueForMissingStub: null);
  @override
  void onTapMenu(_i4.MenuModel? newMenuModel) =>
      super.noSuchMethod(Invocation.method(#onTapMenu, [newMenuModel]),
          returnValueForMissingStub: null);
}
