name: Push docker release
on:
  push:
    branches: [master]

jobs:
  build:
    env:
      REPOSITORY: t_truck_web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: pull last image
        run: docker pull lufemunhoz/t_truck_web:${{ steps.tag_version.outputs.tag }}

      - name: push image
        run: push pull lufemunhoz/t_truck_web:${{ steps.tag_version.outputs.new_tag }}
        # id: docker_build
        # uses: docker/build-push-action@v2
        # with:
        #   pull: true
        #   tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}:${{ steps.tag_version.outputs.new_tag }}
        #   labels: ${{ steps.docker_meta.outputs.labels }}
