name: Push docker homologacao
on:
  push:
    branches: [master]

jobs:
  build:
    env:
      REPOSITORY: t_truck_web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - name: pull last image
        run: docker pull lufemunhoz/t_truck_web:${{ steps.tag_version.outputs.tag }}

      - name: push image
        run: push pull lufemunhoz/t_truck_web:${{ steps.tag_version.outputs.new_tag }}
